name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Oder master, je nachdem wie dein Hauptbranch heißt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Da deine index.html im Root liegt
